config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'admin' => 'admin#index'
  controller :session do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'session/create'
  get 'session/destory'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  #get 'store/index'
  root 'store#index', as: 'store_index'
  resources :products do 
    get :transfer_order_info, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  scope :by_product_id, -> (id) { where ("product_id == id"), id}

  def add_product(product) 
    current_item = line_items.find_by(product_id: product.id)
    if current_item 
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def remove_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item.quantity > 1
      current_item.quantity -= 1
    else
      current_item = line_items.destory
    end
    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :check_cart, only: [:edit, :update, :show, :destory] #DO NOT FORGET TO REMOVE IT LATER
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart)}
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Your cart is curently empty" }
      format.js
      format.json { head :no_content }
    end
  end

  def invalid_cart 
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to  store_index_url, notice: 'Invalid cart'
  end

  def check_cart 
    unless @cart.id == session[:cart_id]
      logger.error "Attempt to access other users cart #{params[:id]}"
      redirect_to  store_index_url, notice: 'Invalid cart'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<span>
  <!--div> 
    <% if notice %>
      <div-- class="notification">
          <%= notice %>
      </div>
    <% end %>
  </div-->

  <h2>Your Cart</h2>

  <% if @cart %>
    <% unless @cart.line_items.empty? %>
      <%= link_to "Empty Cart", @cart, method: :delete, data:{ onfirm: "Are you sure about that?"}, reamote: true, class: 'button' %>
    <% end %>

    <%= render (@cart.line_items) %>

    <% unless (controller.controller_name == 'orders') %>
      <%= button_to 'Checkout', new_order_path, method: :get, class: 'button' %>
    <% end %>
  <% end %>

  <!--div class="content-controls">
    <%= link_to 'Back', store_index_path, class: 'button is-primary' %>
  </div-->
</span>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/destroy.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<% if notice %>
  <div class="notification">
      <%= notice %>
  </div>
<% end %>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>