config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'admin' => 'admin#index'
  controller :session do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'session/create'
  get 'session/destory'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  #get 'store/index'
  root 'store#index', as: 'store_index'
  resources :products do 
    get :transfer_order_info, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  scope :by_product_id, -> (id) { where ("product_id == id"), id}

  def add_product(product) 
    current_item = line_items.find_by(product_id: product.id)
    if current_item 
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def remove_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item.quantity > 1
      current_item.quantity -= 1
    else
      current_item = line_items.destory
    end
    current_item
  end
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :product, optional: true

  validates :label, :body, presence: true
  validates :label, length: {minimum:3}
  validates :body, length: {minimum:10}

  def ensure_if_user_original(comment, current_user)
    if comment.user_id != current_user.id
      raise "Can't delete comment that is not belong to user"
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
  require 'pago'
  has_many :line_items, dependent: :destroy

  enum pay_type: {
    'Check' => 0,
    'Credit card' => 1,
    'Purchase order' => 2,
  }

  validates :name, :email, :address, :pay_type, presence: true
  validates :pay_type, inclusion: pay_types.keys
  validates :email, allow_blank: false, format: {
    with: /.+@.+/,
    message: 'Please enter a valid email address.'
  }
 
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def charge!(pay_type_params)
    payment_details = {}
    payment_method = nil

    case pay_type 
      when "Check"
        payment_method = :check
        payment_details[:routing] = pay_type_params[:routing_number]
        payment_details[:account] = pay_type_params[:account_number]
      when "Credit Card"
        payment_method = :credit_card
        month,year = pay_type_params[:expiration_date].split(//)
        payment_details[:cc_num] = pay_type_params[:credit_card_number]
        payment_details[:expiration_month] = month
        payment_details[:expiration_year] = year
      when "Purchase order"
        payment_method = :po
        payment_details[:po_num] = pay_type_params[:po_number]
    end

      payment_result = Pago.make_payment(
        order_id: id,
        payment_method: payment_method,
        payment_details: payment_details
      )

      if payment_result.succeeded?
        logger.info('Payment succsessfull')
      else
        raise payment_result.error
      end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :comments, dependent: :destroy
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  private 
  def ensure_not_referenced_by_any_line_item  
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
  
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { 
    greater_than_or_equal_to: 0.01,
    message: 'price can`t be empty' 
  }

  validates :title, length: {minimum:3}
  validates :description, length: {minimum:10}

  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

end

app/models/raiting.rb
class Raiting < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  after_destroy :ensure_an_admin_remains
  has_many :comments, dependent: :destroy
  

  validates :name, presence: true, uniqueness: true
  
  has_secure_password

  def ensure_an_admin_remains 
    if User.count == 0 
      raise StandardError.new "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    user_id = session[:user_id]
    @user = User.find_by(id: user_id)
    @total_orders = Order.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  
  def current_controller?(names)
    names.include?(current_controller)
  end

  protected

    def authorize 
      @current_user = User.find_by(id: session[:user_id])

      unless @current_user
        #redirect_to login_url, notice: 'Please log in'

        authenticate_or_request_with_http_basic('Application') do |username, password|
          username == 'Dave' && password == 'hand'
        end
      end 
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :check_cart, only: [:edit, :update, :show, :destory] #DO NOT FORGET TO REMOVE IT LATER
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to cart_url(@cart)}
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_url(@cart), notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Your cart is curently empty" }
      format.js
      format.json { head :no_content }
    end
  end

  def invalid_cart 
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to  store_index_url, notice: 'Invalid cart'
  end

  def check_cart 
    unless @cart.id == session[:cart_id]
      logger.error "Attempt to access other users cart #{params[:id]}"
      redirect_to  store_index_url, notice: 'Invalid cart'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include CountCart
  include CurrentCart
  before_action :set_cart
  skip_before_action :authorize
  
  before_action :get_counter, only: [:index]

  def index
    @products = Product.order(:index)
    @user_interactions = session[:counter]
  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if (condition, record)
    if condition 
      render record
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_nav_bar.html.erb
<nav role="navigation" aria-label="main navigation" class="navbar is-dark">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <figure class="image is-112x28">
        <%= image_tag('logo.jpg') %>
      </figure>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="/">
        Store
      </a>
    
    <% if session[:user_id] %>
      <a class="navbar-item" href="/products/">
        Products
      </a>

      <a class="navbar-item" href="/orders">
        Orders
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Cart
        </a>
        <div class="navbar-dropdown">
          <!--%= render partial: "cart" %-->
        </div>
      </div>
    <% end %>
    </div>

    <div class="navbar-end"> 
      <%= link_to "Log Out", logout_path, method: :delete, data: {confirm: "Are you sure?"}, class:'navbar-item' %>
    </div>

    <!--div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div-->
  </div>
</nav>

app/views/application/_side_bar.html.erb
<aside class="menu">
  <% unless session[:user_id] %>
    <p class="menu-label">
      Sign in
    </p>
    <ul class="menu-list">
      <li> <%= link_to 'Sign In', new_user_path %> </li>
    </ul>
    <ul class="menu-list">
      <li> <%= link_to 'Log In', login_path %> </li>
    </ul>
  <% end %>

  <% if session[:user_id] %>
    <p class="menu-label">
      Products
    </p>
    <ul class="menu-list">
      <li> <%= link_to 'New Product', new_product_path %> </li>
    </ul>
    <ul class="menu-list">
      <li><%= link_to 'Users', users_path %></li>
    </ul>
    <hr>

    <div id="cart">
      <%= render_if @cart && @cart.line_items.any?, @cart %>
    </div>
  <% end %>
  
  <!--ul class="menu-list">
    <li><a>Team Settings</a></li>
    <li>
      <a class="is-active">Manage Your Team</a>
      <ul>
        <li><a>Members</a></li>
        <li><a>Plugins</a></li>
        <li><a>Add a member</a></li>
      </ul>
    </li>
    <li><a>Invitations</a></li>
    <li><a>Cloud Storage Environment Settings</a></li>
    <li><a>Authentication</a></li>
  </ul-->
</aside>