config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'admin' => 'admin#index'
  controller :session do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'session/create'
  get 'session/destory'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  #get 'store/index'
  root 'store#index', as: 'store_index'
  resources :products do 
    get :transfer_order_info, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :comments, dependent: :destroy
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

  private 
  def ensure_not_referenced_by_any_line_item  
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end
  
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: { 
    greater_than_or_equal_to: 0.01,
    message: 'price can`t be empty' 
  }

  validates :title, length: {minimum:3}
  validates :description, length: {minimum:10}

  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart
  include SetComment
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_cart, only: %i[create destory]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_product

  # GET /products or /products.json
  def index
    @products = Product.all.order(:title)
  end

  # GET /products/1 or /products/1.json
  def show
    @comment = Comment.new
    @comments = Comment.find_by(product_id: @product.id)
    session[:product_id] = @product.id
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }

        # @products = Product.all.order(:title)
        # ActionCable.server.broadcast 'products',
        #   html: render_to_string('store/index', layout: false)
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def invalid_product 
    logger.error "Attempt to access invalid product #{params[:id]}"
    redirect_to  store_index_url, notice: 'Invalid product'
  end

  def transfer_order_info 
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    render json: @latest_order
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="column is-two-fifths"> 
  <%= form_with(model: product, local: true) do |form| %>
    <div class="field">
      <%= form.label :title, class: 'label', placeholder: 'Text input' %>
      
      <div class="control">
        <%= form.text_field :title, class: 'input', placeholder: 'Text input'%>
      </div>
    </div>

    <%if product.errors.any? %>
      <div>
        <% product.errors.full_messages_for(:title).each do |message| %>
          <li class="tag is-danger" ><%= message %></li>
        <% end %>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :description, class: 'label', placeholder: 'Title' %>
      
      <div class="control">
        <%= form.text_area :description, class: 'textarea', placeholder: 'Description'%>
      </div>
    </div>

    <%if product.errors.any? %>
      <div>
        <% product.errors.full_messages_for(:description).each do |message| %>
          <li class="tag is-danger" ><%= message %></li>
        <% end %>
      </div>
    <% end %>
    
    <div class="field">
      <%= form.label :price, class: 'label', placeholder: 'Text input' %>
      
      <div class="control">
        <%= form.text_field :price, class: 'input', placeholder: 'Text input'%>
      </div>
    </div>

    <%if product.errors.any? %>
      <div>
        <% product.errors.full_messages_for(:price).each do |message| %>
          <li class="tag is-danger" ><%= message %></li>
        <% end %>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :image_url, class: 'label', placeholder: 'Text input' %>
      
      <div class="control">
        <%= form.text_field :image_url, class: 'input', placeholder: 'Text input'%>
      </div>
    </div>

    <%if product.errors.any? %>
      <div>
        <% product.errors.full_messages_for(:image_url).each do |message| %>
          <li class="tag is-danger" ><%= message %></li>
        <% end %>
      </div>
    <% end %>

    <div class="control">
      <button class="button is-link is-light"> Submit </button>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<nav class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="subtitle is-5">
        <strong>Editing Product</strong>
      </p>
    </div>
  </div>
</nav>
<%= render 'form', product: @product %>
<%= link_to 'Back', products_path, class: 'button is-danger' %>

app/views/products/index.html.erb
<div class="column is-three-fifths">
  <% if notice %>
    <div class="notification">
        <%= notice %>
    </div>
  <% end %>

  <nav class="level">
    <div class="level-left">
      <div class="level-item">
        <p class="subtitle is-5">
          <strong>Products</strong>
          <%= link_to 'New Product', new_product_path, class: 'button' %>
        </p>
      </div>
    </div>
  </nav>

  <% cache @products do %> 
    <% @products.each do |product| %>
      <% cache product do %> 
        <section class="section-medium">
          <div class="content-body">
            <figure class="image is-64x64">
              <%= image_tag(product.image_url)%>
            </figure>

            <h4 class="title is-4"><%= product.title %></h4>
            
            <h4 class="subtitle is-4">
              <%= sanitize(product.description) %>
            </h4>

            <h6 class="subtitle is-6 price"> 
              <%= number_to_currency(product.price)%>
            </h6 class="subtitle is-6">
          </div>

          <br>

          <div class="content-controls">
              <%= link_to 'Edit', edit_product_path(product), class: 'button is-link' %>
              <%= link_to 'Show', product, class: 'button is-primary' %> 
              <%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: 'button is-danger' %>
          </div>
        </section>

        <hr class="has-background-grey-light">
      <% end %>
    <% end %>
  <% end %>

  <br>
</div>

app/views/products/new.html.erb
<nav class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="subtitle is-5">
        <strong>New Product</strong>
      </p>
    </div>
  </div>
</nav>

<%= render 'form', product: @product %>
<%= link_to 'Back', products_path, class: 'button is-danger' %>

app/views/products/show.html.erb
<div class="columns"> 
  <div class="column is-one-third">
    <strong>Title:</strong>
    <div><%= @product.title %></div>
  </div>

  <div class="column is-half">
    <strong>Description:</strong>
    <div><%= @product.description %></div>
  </div>

  <div class="column">
    <figure class="image is-128x128">
        <%= image_tag(@product.image_url) %>
    </figure>
  </div>

  <div class="column">
    <strong>Price:</strong>
    <div><%= @product.price %></div>
  </div>
</div>
<div id="add_comment"> 
  <%= render 'comments/add_comment', comment: @comment%>
</div>
<div id="comment">
  <%= render @product.comments.order(created_at: :desc) %>
</div>
<%= link_to 'Edit', edit_product_path(@product), class: 'button is-link' %>
<%= link_to 'Delete', product_path(@product),
  method: :delete, data: {confirm: "Are you sure?"}, class: 'button is-danger'  %>
<%= link_to 'Back', products_path, class: 'button' %>