config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'admin' => 'admin#index'
  controller :session do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'session/create'
  get 'session/destory'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  #get 'store/index'
  root 'store#index', as: 'store_index'
  resources :products do 
    get :transfer_order_info, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product
  belongs_to :cart
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController 
  include CurrentCart
  before_action :set_cart #, only: %i[create destory]
  before_action :set_line_item, only: %i[show edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_item

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    session[:counter] = 0
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)
    # @cart.line_items.build(product: product)
    # @line_item = LineItem.new(line_item_params)   

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_url }
        format.js { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    if @line_item.cart
      cart = @line_item.cart
    end

    product = @line_item.product

    #@cart.remove_product(product)

    if @line_item.quantity > 1
      @line_item.quantity -= 1
      @line_item.save
    else 
      @line_item.destroy
    end
    
    respond_to do |format|
      format.html { redirect_to url_for(cart), notice: "Line item was removed." }
      format.js { render :action => "reload_cart" }
      format.json { head :no_content }
    end
  end

  def reload_cart
    respond_to do |format|
      format.js { @current_item = @line_item }
    end
  end 

  def invalid_item 
    logger.error "Attempt to access invalid line_item #{params[:id]}"
    redirect_to  store_index_url, notice: 'Invalid item'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def line_item_params
    params.require(:line_item).permit(:product_id)
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<hr>

<% if (line_item == @current_item) && (line_item.quantity <= 1) %>
  <div class="line-item-fade-in">
<% else %>
  <div>
<% end %>
  <article class="media">
    <figure class="media-left">
      <figure class="image is-64x64">
          <%= image_tag(line_item.product.image_url) %>
      </figure>
    </figure>
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= line_item.product.title %></strong>
        </p>
        <p><strong>Count: </strong> <%= line_item.quantity %></p>
        <p><strong>Price: </strong> <%= number_to_currency(line_item.price * line_item.quantity) %></p>
      </div>
      
    </div>
    <div class="media-right">
      <%=link_to '', line_item, method: :delete, remote: true, class: "delete"%>
    </div>
  </article>
</div>

app/views/line_items/create.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<% if notice %>
  <div class="notification">
      <%= notice %>
  </div>
<% end %>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/reload_cart.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

app/views/line_items/show.html.erb
<% if notice %>
  <div class="notification">
      <%= notice %>
  </div>
<% end %>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>